#!/bin/env ruby

require 'rubygems'
require 'right_aws'

#key_info
access_key_id     = "#{ARGV[0]}"
secret_access_key = "#{ARGV[1]}"

#region
ENV["ACW_URL"] = "https://monitoring.ap-northeast-1.amazonaws.com:443/"

#main
rds = Rightscale::RdsInterface.new(access_key_id, secret_access_key, :logger => Logger.new('/dev/null'))
options = { :aws_id => "#{ARGV[2]}",
            :source_type => "db-instance",
            :duration => "9999" }

instances =  rds.describe_events(options)
instances.each do |k|
        s =  k[:date]
        p =  k[:message]
        puts s + ' ' + p
        end
